<a href="https://colab.research.google.com/github/manikanthk123-cpu/NNDL1/blob/main/nndl1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#different tensor representations in neural networks
#Scalar (0-D Tensor)
#to print scalars
import numpy as np
x=np.array(10)
print(x)

10


In [2]:
#to print dimensions
print(x.ndim)

0


In [7]:
#Printing a Vector Using a Python List
vec = [100,200,300,589,547,789]
print(vec)

[100, 200, 300, 589, 547, 789]


In [8]:
#Printing Vector Elements One by One
x= [10,50,100]
for element in x:
  print(element)

10
50
100


In [10]:
#Printing Vector with Index
x = [25 , 30, 45]
for i, val in enumerate(x):
    print(f"Index {i}: {val}")

Index 0: 25
Index 1: 30
Index 2: 45


In [11]:
#Vector (1-D Tensor)
#to print vectors
x=np.array([10,50,100])
print(x)
print(x.ndim)
print(x.shape)

[ 10  50 100]
1
(3,)


In [12]:
#Printing Vector Elements One by One
x=np.array([10,50,100])
#for element in x:
print(x)
print(x.ndim)

[ 10  50 100]
1


In [13]:
#2DMatrix (2-D Tensor)
#to print vectors
import numpy as np
x=np.array([[2,3,4],[6,7,8],[10,11,12]])
print(x)
print(x.ndim)
print(x.shape)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
2
(3, 3)


In [14]:
#3-D Tensor (Images / Time Series) - There are 2 blocks, Each block has 2 rows, Each row has 3 elements
import numpy as np

x = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print(x.ndim)
print(x.shape)

3
(2, 2, 3)


In [15]:
#3-D Tensor (Images / Time Series)
#to print vectors
x=np.array([[[2,3,4],[6,7,8],[10,11,12]],[[2,3,4],[6,7,8],[10,11,12]],[[2,3,4],[6,7,8],[10,11,12]],[[3,4,5],[4,5,6],[6,7,8]]])
print(x)
print(x.ndim)
print(x.shape)
#Color images → (height, width, channels), Video frames and Time-series batches

[[[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 3  4  5]
  [ 4  5  6]
  [ 6  7  8]]]
3
(4, 3, 3)


In [16]:
#4-D Tensor (Batch of Images)
x = np.random.rand(10, 28, 28, 1)  #Batch size → 10 samples, 28 - Image height & width, 1- Number of channels (grayscale image)
print(x.ndim)
print(x.shape)
#Used in CNNs:10 images, 28×28 pixels, 1 channel (grayscale)

4
(10, 28, 28, 1)


In [17]:
#access and manipulate string tensors
import tensorflow as tf
# Create a string tensor
string_tensor = tf.constant(["Alliance", "University", "is great!"])

# String length
string_length = tf.strings.length(string_tensor)
print("String Lengths:", string_length.numpy())

String Lengths: [ 8 10  9]


In [18]:
#Tensor Representation Using TensorFlow
import tensorflow as tf
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [19]:
#Column Vector vs Row Vector
x = np.array([1,2,3])
print(x.reshape(1,3))   # Row vector
print(x.reshape(3,1))   # Column vector


[[1 2 3]]
[[1]
 [2]
 [3]]
